config/routes.rb
Rails.application.routes.draw do
  resources :articles

  get 'about', to: 'pages#about'

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]

  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories

  validates :title, 
    presence: true, 
    length: { minimum: 3, maximum: 50 }

  validates :description, 
    presence: true, 
    length: { minimum: 10, maximum: 300 }

    validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :article_categories
    has_many :article, through: :article_categories

    before_save { self.name = name.downcase }
    validates :name, presence: true, length: { minimum: 3, maximum: 25 }
    validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }

  validates :username, 
            presence: true, 
            uniqueness: {case_sensitive: false},
            length: { minimum: 3, maximum: 25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
            presence: true,
            uniqueness: {case_sensitive: false},
            length: { maximum: 105 },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only: [:edit, :update, :show, :destroy]
	before_action :require_user, except: [:index, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]
	
	def index
		@articles = Article.paginate(page: params[:page], per_page: 5)
	end

	def new
		@article = Article.new
	end

	def edit
	end

	def create
		@article = Article.new(article_params)
		@article.user = current_user

		if @article.save
			flash[:success] = "Post criado!"
			redirect_to article_path(@article)
		else
			render 'new'
		end
	end

	def update
		if @article.update(article_params)
			flash[:success] = "Post atualizado!"
			redirect_to article_path(@article)
		else
			render 'edit'
		end
	end

	def show
	end

	def destroy
	  @article.destroy
	  flash[:danger] = "Post deletado!"
	  redirect_to articles_path
	end

	private
	  def article_params
		params
		.require(:article)
		.permit(
		  :title,
			:description,
			category_ids: []
		)
	  end

	  def set_article
	  	@article = Article.find(params[:id])
		end
		
		def require_same_user
			if current_user != @article.user and !current_user.admin?
				flash[:danger] = "Você só pode editar/deletar seus próprios posts!"
				redirect_to articles_path
			end
		end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:index, :show]

    def index
        @categories = Category.paginate(page: params[:page], per_page: 5)
    end

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)

        if @category.save
            flash[:success] = "Categoria criada!"
            redirect_to categories_path
        else
            render 'new'
        end
    end

    def edit
        @category = Category.find(params[:id])
    end

    def update
        @category = Category.find(params[:id])

        if @category.update(category_params)
            flash[:success] = "Categoria atualizada!"
            redirect_to category_path(@category)
        else
            render 'edit' 
        end
    end

    def show
        @category = Category.find(params[:id])
        @category_articles = @category.article.paginate(page: params[:page], per_page: 5)
    end

    private

    def category_params
        params
        .require(:category)
        .permit(:name)
    end

    def require_admin
        if !logged_in? or (logged_in? and !current_user.admin?)
            flash[:danger] = "Somente admins podem realizar esta ação!"
            redirect_to categories_path
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		redirect_to articles_path if logged_in?
	end

	def about
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.where(email: params[:session][:email].downcase).first

		if user and user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			redirect_to user_path(user)
			flash[:success] = "olá =)"
		else
			flash.now[:danger] = "Email não existe ou senha está incorreta"
			render 'new'
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:success] = "tchau =("
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:edit, :update, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]
	before_action :require_admin, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end
  
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)

		if @user.save
			session[:user_id] = @user.id
  		flash[:success] = "Bem vindo(a) ao blog #{@user.username}"
  		redirect_to user_path(@user)
  	else
  		render 'new'
  	end
  end

  def edit
  end

  def update
		if @user.update(user_params)
  		flash[:success] = "Atualizações feitas com sucesso!"
  		redirect_to articles_path
		else
  		render 'edit'
    end
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
	end
	
	def destroy
		@user = User.find(params[:id])
		@user.destroy
		flash[:danger] = "Usuários e todos os artigos criados por ele deletados!"
		redirect_to users_path
	end

  private
    def user_params
    	params
    	.require(:user)
    	.permit(
    	  :username,
    	  :email,
    	  :password
    	)
		end
		
		def set_user
			@user = User.find(params[:id])
		end

		def require_same_user
			if current_user != @user and !current_user.admin?
				flash[:danger] = "Você só pode editar sua própria conta!"
				redirect_to root_path
			end
		end

		def require_admin
			if logged_in? and !current_user.admin?
				flsh[:danger] = "Somente admins podem realizar esta ação!"
				redirect_to root_path
			end
		end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def gravatar_for(user, options = { size: 80 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.username, class: "img-circle")
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
<div class="row">
	<div class="col-xs-8 col-xs-offset-2">
		<div class="well well-lg">
			<div class="article-title">
				<%= link_to article.title, article_path(article) %> 
			</div>
			<div class="article-body">
				<%= truncate(article.description, length: 100) %>
				<div class="article-meta-details">
					<small>
						Criado por: <%= article.user.username if article.user %>
						(<%= time_ago_in_words(article.created_at) %>)
						 - última atualização: <%= time_ago_in_words(article.updated_at) %>
					</small>
				</div>
			</div>
			<% if article.categories.any? %>
				<p>Categorias: <%= render article.categories %>
			<% end %>
			<% if logged_in? and (current_user == article.user or current_user.admin? ) %>
				<div class="article-actions">
					<%= link_to "Editar post", edit_article_path(article), class: "btn btn-xs btn-primary" %>
					<%= link_to "Deletar post", article_path(article), 
													method: :delete, 
													data: {confirm: "Tem certeza?"}, 
													class: "btn btn-xs btn-danger" %>
				</div>
			<% end %>
		</div>
	</div>
</div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
	<div class="col-md-12">
		<%= form_for @article, :html => {class: "form-horizontal", role: "form"} do |f| %>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :title, "Título" %>
				</div>
				<div class="col-sm-10">
					<%= f.text_field :title, class: "form-control", placeholder: "Título", autofocus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :description, "Texto" %>
				</div>
				<div class="col-sm-10">
					<%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Texto", autofocus: true %>
				</div>
			</div>

			<div class="form-group">
				<div class="row">
					<div class="col-sm-offset-2 col-sm-8">
					<%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
						<% cb.label(class: "checkbox-inline input_checkbox") { cb.check_box(class:"checkbox") + cb.text } %>
					<% end %>
					</div>
				</div>
			</div>

			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
					<%= f.submit "Salvar" ,class: 'btn btn-primary btn-lg' %>
				</div>
			</div>
		<% end %>		

		<div class="col-xs-2 col-xs-offset-2">
			[ <%= link_to "voltar para Posts", articles_path %> ]
		</div>
	</div>
</div>

app/views/articles/edit.html.erb
<div class="row">
	<div class="col-xs-4 col-xs-offset-2">
		<h1>Editar post</h1>
	</div>
</div>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Posts</h1>

<div align="center">
	<%= will_paginate %>
</div>

<%= render 'article', obj: @articles %>

<div align="center">
	<%= will_paginate %>
</div>

app/views/articles/new.html.erb
<div class="row">
	<div class="col-xs-4 col-xs-offset-2">
		<h1>Novo Post</h1>
	</div>
</div>

<%= render 'form' %>

app/views/articles/show.html.erb
<!-- article title -->
<h2 align="center"><%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
	
	<!-- user information -->
	<% if @article.user %>
		<ul class="listing">
			<div class="row center">
				<div class="col-md-4 col-md-offset-4">
					<li>Criado por:</li>
					<li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
					<li class="article-title"><%= link_to @article.user.username, user_path(@article.user) %></li>
					<li>
						<small>
							<%= pluralize(@article.user.articles.count, "post") if @article.user.articles %>
						</small>
					</li>
				</div>
			</div>
		</ul>
	<% end %>

	<!-- article description -->
	<%# <h4 class="center description">
		<strong>Texto:</strong>
	</h4> %>
	<hr>
	<%= simple_format(@article.description) %>

	<!-- -->
	<% if @article.categories.any? %>
		<p> Categorias: <%= render @article.categories %>
	<% end %>

	<!-- articles actions -->
	<div class="article-actions">
		<% if logged_in? and (current_user == @article.user or current_user.admin?) %>
			<%= link_to "Editar post", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
			<%= link_to "Deletar post", article_path(@article), method: :delete, 
												data: {confirm: "Tem certeza?"}, 
												class: "btn btn-xs btn-danger" %>
		<% end %>
		<%= link_to "voltar para Posts", articles_path, class: "btn btn-xs btn-success" %>	
	</div>
</div>

app/views/categories/_category.html.erb
<span class="badge">
    <%= link_to category.name, category_path(category) %>
    &nbsp;
</span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<%= form_for @category, :html => {class: "form-horizontal", role: "form"} do |f| %>
    <div class="form-group">
        <div class="control-label col-sm-2">
            <%= f.label :name %>
        </div>
        <div class="col-sm-10">
            <%= f.text_field :name, class: "form-control", placeholder: "Category name", autofocus: true %>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
    </div>
<% end %>

app/views/categories/edit.html.erb
<div class="row">
    <div class="col-xs-4 col-xs-offset-2">
        <h1>Edit Category</h1>
    </div>
</div>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center">Categorias</h1>
<div align="center" >
    <%= will_paginate %>
    <% @categories.each do |category| %>
        <ul class="listing">
            <div class="row">
                <div class="well col-md-4 col-md-offset-4">
                    <li class="article-title">
                        <%= link_to "#{category.name}", category_path(category) %>
                    </li>
                    <li>
                        <small><%= pluralize(category.article.count, "post") %></small>
                    </li>
                </div>
            </div>
        </ul>
    <% end %>
    <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<div class="row">
    <div class="col-xs-4 col-xs-offset-2">
        <h1>New Category</h1>
    </div>
</div>

<%= render 'shared/errors', obj: @category %>

<%= form_for @category, :html => {class: "form-horizontal", role: "form"} do |f| %>
    <div class="form-group">
        <div class="control-label col-sm-2">
            <%= f.label :name %>
        </div>
        <div class="col-sm-10">
            <%= f.text_field :name, class: "form-control", placeholder: "Category name", autofocus: true %>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
    </div>
<% end %>		

<div class="col-xs-2 col-xs-offset-2">
    [ <%= link_to "Back to articles listing", articles_path %> ]
</div>

app/views/categories/show.html.erb
<h1 align="center"><%= @category.name %></h1>

<div align="center">
    <% if logged_in? and current_user.admin? %>
        <div class="row">
            <span class="badge">
                <%= link_to "Edit Category", edit_category_path(@category) %>
            </span>
        </div>
        <br/>
    <% end %>
	<%= will_paginate @category_articles %>
</div>

<%= render 'articles/article', obj: @category.article %>

<div align="center">
	<%= will_paginate @category_articles %>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
	<footer class="footer">
		<small>
			Copyright &copy; 2017
		</small>
		<nav>
			<ul>
				<li><%= link_to "Sobre", about_path %></li>
			</ul>
		</nav>
	</footer>	
</div>

app/views/layouts/_messages.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<% flash.each do |name, msg| %>
			<div class='alert alert-<%= "#{name}" %>'>
				<a href="#" class="close" data-dismiss="alert">&#215;</a>
				<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "my blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Posts", articles_path %></li>

        <!-- Article actions if logged in -->
        <% if logged_in? %>
        <li><%= link_to "Usuários", users_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Ações <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Novo Post", new_article_path %></li>
            <%# <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li> %>
          </ul>
        </li>
        <% end %>

        <!-- Categories -->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categorias <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Todas as categorias", categories_path %></li>
            <% Category.all.each do |category| %>
              <li><%= link_to "#{category.name}", category_path(category) %></li>
            <% end %>

            <!-- Only for admins options -->
            <% if logged_in? and current_user.admin? %>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Nova categoria", new_category_path %></li>
            <% end %>
          </ul>
        </li>
      </ul>
      <%# <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> %>
      <ul class="nav navbar-nav navbar-right">
        <li>
        <% if logged_in? %>
          <%= link_to 'Sair', logout_path, method: :delete %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Perfil <%= " (Admin)" if current_user.admin? %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Editar meu perfil", edit_user_path(current_user) %></li>
              <li><%= link_to "Ver meu perfil", user_path(current_user) %></li>
              <%# <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li> %>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log in', login_path %></li>
          <li><%= link_to 'Sign Up', signup_path %></li>
        <% end %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>

    <div class="container">
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Sobre</h1>

app/views/pages/home.html.erb
<div class="row">
  <!-- Blog Entries Column -->
  <div class="col-md-8">
    <!-- Home image -->
    <div class="card mb-4">
      <div class="center jumbotron">
        <h1>my blog</h1>
        <%= link_to "cadastre-se", signup_path, class: "btn btn-warning btn-lg btn-xlarge" %>
      </div>
    </div>
  </div>
  <!-- Sidebar Widgets Column -->
  <div class="col-md-4">
    <!-- Sobre -->
    <div class="card my-4">
      <%= image_tag("yellow.jpg", class: "img-thumbnail") %>
      <h5 class="card-header">Sobre</h5>
      <div class="card-body">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut porttitor urna. Ut lacinia faucibus rutrum. Nulla facilisi. Nunc fermentum laoreet dui ut finibus. Praesent nisi felis, interdum vitae risus tincidunt, pharetra tempus orci. Morbi et sagittis risus, in hendrerit elit. Mauris a velit mauris. Nullam vehicula, augue in egestas venenatis, justo ex porta tortor, eget bibendum turpis elit et ex. Nullam vitae maximus felis, eu consectetur risus. Vivamus rutrum lobortis odio ut vestibulum. Cras mollis ut libero sit amet efficitur.
      </div>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<div class="panel panel-danger">
				<div class="panel-heading">
					<h2 class="panel-title">
						<%= pluralize(obj.errors.count, "error") %>
						prohibited this article from being saved:
					</h2>
					<div class="panel-body">
						<ul>
							<% obj.errors.full_messages. each do |msg| %>
							<li><%= msg %></li>
							<% end %>
						</ul>
					</div>
				</div>
			</div>
			
		</div>
	</div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class="row">
	<div class="col-md-12">
		<%= form_for @user, :html => {class: "form-horizontal", role: "form"} do |f| %>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :username %>
				</div>
				<div class="col-sm-10">
					<%= f.text_field :username, class: "form-control", placeholder: "Username", autofocus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :email %>
				</div>
				<div class="col-sm-10">
					<%= f.email_field :email, class: "form-control", placeholder: "Email" %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :password %>
				</div>
				<div class="col-sm-10">
					<%= f.password_field :password, class: "form-control", placeholder: "Password" %>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
				<% if @user.new_record? %>
				  <%= f.submit "Salvar", class: 'btn btn-primary btn-lg' %>
				<% else %>
				  <%= f.submit "Salvar mudanças", class: 'btn btn-primary btn-lg' %>
				<% end %>
				</div>
			</div>
		<% end %>		

		<div class="col-xs-2 col-xs-offset-2">
			[ <%= link_to "voltar para Posts", articles_path %> ]
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<div class="row">
	<div class="col-xs-4 col-xs-offset-2">
		<h1>Editar perfil</h1>
	</div>	
</div>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">Todos os usuários</h1>

<div align="center">
	<%= will_paginate %>

	<% @users.each do |user| %>
	<ul class="listing">
		<div class="row">
			<div class="well col-md-4 col-md-offset-4">
				<li><%= link_to gravatar_for(user), user_path(user) %></li>
				<li class="article-title"><%= link_to user.username, user_path(user) %></li>
				<li>
					<small><%= pluralize(user.articles.count, "post") if user.articles %></small>
				</li>
				<% if logged_in? and current_user.admin? %>
				<li><%= link_to "Delete this user", user_path(user), method: :delete, data: {confirm: "Are you sure?"}, 
				class: "btn btn-xs btn-danger" %></li>
				<% end %>
			</div>
		</div>
	</ul>
	<% end %>

	<%= will_paginate %>
</div>

app/views/users/new.html.erb
<div class="row">
	<div class="col-xs-4 col-xs-offset-2">
		<h1>Sign Up</h1>
	</div>	
</div>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Olá <%= @user.username %></h1>

<div class="row">
	<div class="col-md-4 col-md-offset-4 center">
		<%= gravatar_for @user, size: 150 %>
	</div>
</div>
<hr/>

<h3 align="center">posts feitos por <%= @user.username %></h3>

<div align="center">
	<%= will_paginate @user_articles %>
</div>

<%= render 'articles/article', obj: @user_articles %>

<div align="center">
	<%= will_paginate @user_articles %>
</div>